TASEmulators/desmume

.gitignore

Visual Studio 2015 produces an extra .VC.db file when building any
solution

gitignore: Visual Studio 2015 database

---

desmume/src/commandline.cpp

In commandline.cpp, instead of copying the user-supplied paths to bios images, you are copying the uninitialized destination variables meant to contain these paths *to themselves*. This PR fixes that.

copy paths to variables rather than uninitialized data

---

desmume/src/commandline.cpp
desmume/src/commandline.h
desmume/src/rtc.cpp
desmume/src/rtc.h

--rtc-day and --rtc-hour may be used to override the emulated time.
rtc-day is a day of week (0-6) rtc-hour is the hour (0-23). Time
difference is calculated at emulator start and the emulated RTC then
reports time from the future. This difference is then maintained so that
an hour after the emulator is started means an hour passes according
to the RTC.

Add rtc-day/hour options to override NDS clock

---

desmume/src/ROMReader.cpp

This was omitted in c365617ff737bdb3c06c307159078ca4e5f7e175; the other
ROMReader_structs it updated were correct.

fix: add missing comma in ZIPROMReader definition

---

desmume/src/frontend/posix/shared/mic_alsa.cpp
desmume/src/frontend/posix/shared/mic_openal.cpp
desmume/src/mic.cpp

11cf901336d77574e0f2c3482e130e05fa5f03e4 changed most of these but
missed these three.

Update remaining stub versions of mic_savestate/loadstate.

---

desmume/src/frontend/posix/cli/main.cpp

f5c9a36930f1fa0889e89080e210063bee623172 tried to remove an entry from
the list of options, but only deleted half of it.

Fix broken option list in POSIX frontend

---

desmume/src/frontend/posix/gtk/main.cpp

This was lost in 0869afded6315fb14d2265e8b3872b36ccc3fdce's refactoring.

Linux Port: Fix missing semicolon.

---

desmume/README.LIN

I found these dependencies harder to figure out than usual, 
since I'm used to installing packages with pregenerated `configure` scripts.
In particular if `glib` is missing then `configure` will generate with unexpanded macros, which is confusing.
This extra paragraph should be helpful for others. 
Thanks for a great program :)

Update README.LIN (autogen.sh, dependencies)

---

desmume/src/frontend/windows/main.cpp

Noticed that a recent Windows update made my touch screen work unexpectedly with desmume, perhaps a bad driver issue or a change in how Windows interprets touch screen input as mouse events.
Regardless, I added support for some of the [WM_POINTER* family of messages](https://msdn.microsoft.com/en-us/library/hh454903(v=vs.85).aspx) which fixed the issue.

Windows Port: Adding Pen and Touch support for touch screen devices

---

desmume/src/frontend/windows/main.cpp
desmume/src/frontend/windows/video.h

DeSmuME currently allocates 5 times the RAM required for video, in case the user selects the 5x magnification filter. This is mainly a problem when using a high 3D scaling factor.
These commits remove this excess usage of RAM by only allocating as much as is required for the currently selected filter.

Reduce RAM usage

---

desmume/src/frontend/windows/main.cpp

Currently, DeSmuME will skip frames if the display thread cannot keep up with emulation. Thus the user sees frame skipping even when fame skip is set to 0. This commit has DeSmuME wait for the display to update (up to 500ms) each frame before calling Display() again.
This does not, however, let the display/HUD skip frames when frame skip is set to anything other than 0. The frame skip option still does not affect the display thread, so the user will see an updated HUD each frame.

Do not allow skipping display frames (except in extreme lag).

---

desmume/src/mc.cpp
desmume/src/mc.h
desmume/src/movie.cpp

isMovieMode was removed because while playing a movie, the EMUFILE will always be an EMUFILE_MEMORY created for the movie, so there's no need to protect against overwriting the user's .dsv file on disk. (Writing to the EMUFILE must be allowed during movies to avoid getting an in-game error for not being able to write to the save file.)

Properly handle SRAM while playing movies.

---

desmume/src/frontend/modules/osd/agg/agg2d.h
desmume/src/frontend/posix/configure.ac

Upstream AGG version 2.5 is dead and the 2.4 version was forked and is developed seperatly at https://sourceforge.net/projects/agg/
Since this request just removes the enumeartions for new features in the discontinued AGG 2.5, which were never used in desmume, it should compile under both versions of AGG.

revert to agg >= 2.4

---

desmume/src/wifi.cpp

Save ethernet packets to pcap files only if the defined WIFI_LOGGING_LEVEL >= 3

Don't save ethernet packets to pcap files by default.

---

desmume/src/frontend/windows/main.cpp
desmume/src/frontend/windows/resource.h
desmume/src/frontend/windows/resources.rc

The right hand screen is allowed to be resized in horizontal screen layout to enable the window or full screen display to better utilize the screen area.
Changes:
1- Modify scaling, resizing and update functions to allow for new screen resizing ratio
2- Modify touch input scaling (incl. HUD editing) to adapt to different screen sizes
3- Add GUI menu for user to select the screen resizing ratio
4- Implement saving/loading settings from file similar to other settings

(Windows Frontend) Allow screen resizing in horizontal display layout.

---

desmume/src/frontend/windows/main.cpp

Fix missing division in ScaleScreen function which caused window size to increase on each startup  if screen size ratio > 1.

(Windows Frontend) Fix window size increase on startup

---

.gitignore
desmume/src/frontend/windows/hotkey.cpp
desmume/src/frontend/windows/main.cpp
desmume/src/frontend/windows/main.h
desmume/src/frontend/windows/resource.h
desmume/src/frontend/windows/resources.rc

Added the following Options:
1- Windowed Fullscreen mode (fixes #164), assuming user turns off vsync option in desmume as DWM will handle that
2- Show menu in full screen mode, and fixed settings changes (from menu or hotkey) that break window size
3- Auto-hide cursor option (Full screen mode)
Fixes:
1- Screen gap is no longer visible in horizontal layout when the window is resized when using opengl display method if the layout was changed from vertical to horizontal without restarting the emulator
2- No longer possible to rotate the video using hotkey in horizontal layout
3- Changing layout from vertical to horizontal while video is rotated and windowsize = 0 no longer increases window size
4- Changing screen layout while screensizeratio is > 1 and windowsize = 0 no longer increases …

(Windows Frontend) Add Fullscreen Options And Window Sizing Fixes

---

desmume/src/gfx3d.cpp

If the position test register is negative, conversion to unsigned
integer is undefined. This breaks games on arm64 where the behaviour is
defined as 'truncate to zero'. Converting to a signed integer first
guarantees the intended behaviour.

Fix undefined behaviour converting 3D postest registers

---

desmume/src/frontend/windows/console.cpp

Currently under Windows 1803 and 1809 (maybe other windows versions as well), when disabling console, it will only detach from the Desmume process and continue to stay open and visible. Since I don't really know much about the console and how to fix it, we should just hide the window for now.

[Windows] Hide the console window in the current session when disabling in menu.

---

desmume/src/frontend/posix/gtk/main.cpp

Gtk+ Port: Use Desktop or Home as fallback directory for screenshots

---

desmume/src/frontend/posix/gtk-glade/callbacks.cpp
desmume/src/frontend/posix/gtk/main.cpp

The screenshot function no longer overwrites screenshots from previous sessions

don't clobber existing screenshots

---

desmume/src/frontend/windows/DeSmuME.vcxproj
desmume/src/frontend/windows/desmume.props

Fixes MSVC2019 solution loading and compiling.
Due to 2019 dropping XP support by default, anyone needing XP compiles will need to download the v141 toolkit as an extra and manually configure TargetPlatform and PlatformToolset.

Fix MSVC2019 solution loading and compiling

---

desmume/src/cheatSystem.cpp

This PR fixes a regression issue with the Action Replay DS cheat handler that was reintroduced when it was rewritten in 6abf2b3. Currently, the cheat handler does not skip over the extra lines of code type 0x0E (Patch Code) when execution status is _false_.
Consider the following ARDS code:
```
52000000 AAAAAAAA
E2000000 00000008
D2D2D2D2 D2D2D2D2
02000008 BBBBBBBB
D2000000 00000000
```
When the word at `0x02000000` does not equal `0xAAAAAAAA`, the cheat handler is supposed to skip over all following codes until a 0xD0 or 0xD2 code is encountered. But because the `0xD2D2D2D2` written by the 0x0E code is not skipped, the cheat handler interprets this as a 0xD2 code and resets execution status prematurely. As a result, the value `0xBBBBBBB` is written to `0x02000008` even though the …

Fix Action Replay DS code type 0x0E

---

desmume/src/frontend/windows/display.cpp
desmume/src/frontend/windows/display.h
desmume/src/lua-engine.cpp

This change adds a Lua function called `gui.setlayermask`, which allows Lua scripts to procedurally modify which render layers are visible. It takes two arguments: one integer bitfield representing the visibility states for the main GPU, and the other representing the sub GPU. For example: `0b11111` shows all layers, `0b00000` hides all layers, `0b00001` shows only layer 0 (`BG0`), `0b10000` shows only layer 5 (`OBJ`), etc.
Since display layer state is coupled to the frontend, and since frontends are entirely separate between platforms _(i.e., on Windows, toggling display layer state requires updating the GUI state as well)_, this function is only supported and tested on the Windows build. On MacOS and Linux, `gui.setlayermask` will simply return 0 without doing anything.
I added this …

Add Lua function gui.setlayermask

---

desmume/src/lua-engine.cpp

This is a tiny follow-up to PR #273, with no actual changes in functionality. In short:
- `gui.setlayermask(top, bottom)` &rarr; `gui.setlayermask(main, sub)`
Display layers correspond to the GPU _(main or sub)_, not to screen _(top or bottom)_, so this change just updates the Lua parameter names to reflect that.
I wasn't aware of that discrepancy until I tested a bit more, and I didn't want to introduce screen/GPU confusion into the codebase. NRN thx dawg

Clarify parameter names for gui.setlayermask

---

desmume/src/frontend/windows/resources.rc

Since full text unable to read when it was `35`, changed to `71`, so its readable right now.
Typo corrected
Added Windows Border to sound setting to make it more important
“Wi-fi” [is used to certify the interoperability of wireless computer networking devices](https://www.merriam-webster.com/dictionary/Wi-Fi). So `Wifi `changed to `Wi-fi`

typo related updates

---

desmume/src/frontend/posix/gtk/config_opts.h
desmume/src/frontend/posix/gtk/main.cpp
desmume/src/frontend/posix/shared/sndsdl.cpp
desmume/src/frontend/posix/shared/sndsdl.h

This is a request to add the "Set audio volume" menu item to the posix GTK front end of desmume.
Go to "Config > Set audio volume" to set the audio volume.
A slider helps to set the audio volume between 0 and 128.
This feature is already included in a lot of emulators like fceux (Nintendo Entertainment System) or visualboyadvance-m (Nintendo Game Boy) so I think it makes sense for desmume (Nintendo DS) to do it too.
Moreover, this new menu item will let the user set the audio volume directly inside desmume without using an external mixer included in the operating system.
This is more straightforward.
* desmume/src/frontend/posix/gtk/config_opts.h: Add the "audio_volume" option.
* desmume/src/frontend/posix/gtk/main.cpp: Add the "setaudiovolume" menu item.
* …

Add the "Set audio volume" menu item

---

desmume/src/frontend/posix/gtk/config_opts.h
desmume/src/frontend/posix/gtk/main.cpp

This is a request to add the "Set firmware language" menu item to the posix GTK front end of desmume.
Go to "Config > Set firmware language" to set the firmware language.
Here, check the checkbox to enable the command line overriding.
After that, you can choose the firmware language through a combo box.
Desmume already offers to set the firmware language on the command line.
For example, you can set the french language:
```
$ desmume --lang 2
```
However, having a menu item to set the firmware language is more user-friendly.
For those who like specifying the firmware language on the command line, it is not a problem because it is always possible and it is the default.
* desmume/src/frontend/posix/gtk/config_opts.h: Add the "command_line_overriding_firmware_language" option.
* …

Add the "Set firmware language" menu item

---

desmume/src/frontend/posix/gtk/main.cpp

This is a fix to avoid a GTK warning in the posix front end of desmume.
Indeed, the current behavior when `View > Screen Gap` is enabled is the following:
```
$ gtk/desmume
[...]
(desmume:13420): Gtk-CRITICAL **: 08:17:58.755: IA__gtk_widget_set_size_request: assertion 'GTK_IS_WIDGET (widget)' failed
[...]
```
Now, with this fix, this warning is gone.
* desmume/src/frontend/posix/gtk/main.cpp(common_gtk_main): Modify a multiline comment to be a single line comment.
* desmume/src/frontend/posix/gtk/main.cpp(common_gtk_main): Add a comment to indicate that moving the following instruction implies that a GTK warning is shown.
* desmume/src/frontend/posix/gtk/main.cpp(common_gtk_main): Move a statement later to avoid a GTK warning.

Move a statement later to avoid a GTK warning

---

desmume/src/SPU.cpp

This fixes crackling when using small streamed-audio buffers and correctly interpolates chip-style samples. Also, a slight edit for consistency across the PCM8 and PCM16 fetching functions.

Add interpolation at loop boundary

---

desmume/src/wifi.cpp

Tiny fix to include _offsetof_ inbuilt declaration to compile with modern gcc.

Fix to compile with gcc

---

desmume/src/frontend/posix/gtk/main.cpp

Fixes #309 by setting the background color to black when enabling fullscreen and setting it back to the default color when returning to window mode.

set fullscreen background to black for gtk frontend

---

desmume/src/frontend/posix/cli/main.cpp
desmume/src/frontend/posix/gtk-glade/main.cpp
desmume/src/frontend/posix/gtk/main.cpp

The build failure(s) come from the fact that the posix frontends currently
use deprecated functions for multi-threading. The offending functions are:
g_thread_create and g_thread_supported, both deprecated since 2.32.
This patch fixes issue #304 by replacing g_thread_create with g_thread_new.
g_thread_supported is removed as it's no longer needed at all for glib >= 2.32
threading is automatically initialized when the program starts.

Issue: can't compile on Arch Linux #304

---

desmume/src/frontend/posix/configure.ac
desmume/src/frontend/posix/gtk-glade/main.cpp

Update `GLADEUI_UNINSTALLED_DIR` to work with the current directory layout.
Also adds a failure message when the glade ui file is not found.

Fix glade UI file path in local builds

---

desmume/src/OGLRender_3_2.cpp

Should fix #126 and #202 
I'm worried that this might hide errors because it silently ignores them if it can't read an extension name. Maybe it's better to crash or log that the value was null?

Fix unhandled null causing crash when using osmesa with nvidia driver

---

desmume/src/frontend/posix/gtk/config_opts.h
desmume/src/frontend/posix/gtk/main.cpp

a289055e removed the code that updated the old "multisampling enabled"
config. This fix adds a new config value for the multisampling size and
updates the old config in sync. When loading the config, the new
multisampling size value is prioritized, but if it is 0 (possibly not set)
then it falls back to the previous logic using the old boolean config
value.

Linux GTK Port: Fix config for new MSAA options

---

desmume/src/frontend/posix/gtk/main.cpp

GTK: fix audio interpolation mode not being saved or loaded from config

---

desmume/src/utils/vfat.cpp

Checking whether the current directory is a directory (instead of current entry) may lead to "pop" command issued on an empty stack, which in turn SEGV desmume.

Fix directory crawling on symlink-capable systems

---

desmume/src/frontend/posix/gtk/main.cpp

This restores fullscreen and window resize not changing the content area size, and a build issue. Sorry about that.

Fix two issues in the recent GTK+ move

---

desmume/src/frontend/posix/gtk/main.cpp

Orientation is passed as string, actual orientation name, not a number.

GTK: fixed LCD layout switching

---

desmume/src/frontend/posix/gtk/main.cpp

Only the first of the positional arguments is interpreted as the ROM’s filename, because we don’t emulate multiple ROMs at once.
Fixes #382.

GTK: Fix opening a ROM from the command line

---

desmume/src/frontend/posix/gtk/main.cpp

This pull request is a rebase of https://github.com/TASVideos/desmume/pull/347 .  When I originally submitted this, there was a lot of recent changes to the gtk code in desmume.  I finally got around to rebasing this against the latest gtk changes in desmume
This branch adds "Import Backup Memory" and "Export Backup Memory" entries to the GTK File menu.  Previously, this functionality was only available on the win32 version.

gtk: add import/export memory menu items

---

desmume/src/frontend/posix/cli/meson.build
desmume/src/frontend/posix/gtk-glade/meson.build
desmume/src/frontend/posix/gtk/meson.build

Use standard function `install_man` which automatically determines the mandir and `man[0-9]` instead of guessing. Now it respects the `--mandir` option.
By default it's set to `--mandir=share/man`, which is where it was installing.

GTK: Use standard meson to install man pages

---

desmume/src/GPU.cpp
desmume/src/filter/videofilter.cpp
desmume/src/libretro-common/include/rthreads/rthreads.h
desmume/src/libretro-common/rthreads/rthreads.c
desmume/src/rasterize.cpp
desmume/src/utils/task.cpp
desmume/src/utils/task.h
desmume/src/wifi.cpp

This makes it much more easy to figure out why a given thread is consuming CPU time for instance.
This is still missing sound threads, but those depend on SDL apparently.

Give thread names to ease debugging

---

desmume/src/version.cpp

Adds aarch64 to the lists of available DESMUME_PLATFORM_STRINGs.
Cherry-picked from 0d763b350a3ce0de7ee4d965ca54c5f3af4373f8.

Add aarch64 string

---

desmume/src/frontend/posix/gtk/config_opts.h
desmume/src/frontend/posix/gtk/main.cpp

Changing save type was working internally, but was not reflected in the menu or config file.

Update menu and config upon save type change

---

desmume/src/frontend/posix/gtk/main.cpp

Background events for joysticks need to be explicitly enabled, otherwise they only work when SDL window has focus apparently.

GTK: fix freeze when editing joystick controls

---

desmume/src/frontend/posix/gtk/main.cpp
desmume/src/frontend/posix/gtk/main.ui

This PR updates #403 for the current desmume-gtk (Linux) code.
Up until now, the Desmume looked like the picture below on my machine (and perhaps Linux machines in general)
The light backgrounds were an eyesore. This commit changes the background color to black and the status bar text to a light gray so that it is readable on the black background.
It's obviously not perfect: the toolbar is still light-themed (I hope to fix this at some point by defaulting to a dark GTK theme), and the buttons still become a whiteish color on hover (a theming issue). However the current solution is good enough in fullscreen, where the clashing elements are hidden. I was hoping to get this merged for now

Change background color on Linux

---

desmume/src/frontend/posix/gtk/main.cpp

I did some digging after #467. Unless I'm missing something, the file-based state loads/stores actually work just fine on Linux/GTK: they're just disabled. This PR enables them, and also disables save/load functionality in some situations where it just crashes the emulator currently.

Enable "Save state to" and "Load state from" functionality in GTK

---

desmume/src/frontend/posix/gtk/main.cpp

PR #481 is a bit messed up, it re-adds a commit that's already merged (the first one), then adds a merge-commit undoing that commit. merging it as-is would cause hick-ups with tools that automatically process git history.
i cherry-picked the only commit that's good and put it into this new PR, plus added a fixup commit that removes the gratuitous memset, and uses the secure snprintf instead of sprintf.
whether the commit itself is reasonable is unknown, as i dont know whether in this context a stack-allocated buffer can be used, so it's probably best if the author of the GTK+3 port takes a look at it.
the steps i took for the cleaning up were:
```sh
git checkout master
git checkout -b pr481new
wget -c https://github.com/TASEmulators/desmume/pull/481/commits/61082687d12bb917263ce5003352a87c …
```

PR 481 redone

---

desmume/src/frontend/interface/draw_sdl_window.cpp

Memory leak occurred in binary interface's draw_sdl_window.cpp `sdl_draw_no_opengl` method
A call to the `SDL_DestroyTexture` method was forgotten, resulting in all the textures created to render the game's frames being stored indefinitely until running out of memory
This is a temporary fix so anyone using the interface (mainly `py-desmume` users) can have it working correctly again. Next step is to mirror the changes from POSIX CLI's main.cpp `Draw` method, if stable

Hotfix: fixed memory leak in binary interface

---

desmume/src/frontend/posix/gtk/main.cpp

According to RFC 2396, the single quote character (') is allowed in uri
strings and is not escaped by gtk, so the action string constructed for
the recent files menu must be quoted with " instead of '.
This fixes issue #437

Linux: Fix recent entries with quote in filename

---

desmume/src/frontend/posix/gtk/main.cpp
desmume/src/frontend/posix/gtk/menu.ui

This adds the view menu back as pop-up menu, which was disabled by the
gtk2 port.
This fixes issue #407.

Linux: Add pop-up menu back

---

desmume/src/frontend/posix/gtk/desmume.cpp
desmume/src/frontend/posix/gtk/main.cpp

Since NDS_Init() takes no arguments, it should not hurt to call it early
in the gtk frontend, too.
This fixes the segfault in issue #415

Linux: Call NDS_Init() early

---

.github/workflows/build.yml

This pull-request adds macOS app (means `DeSmuME.app`) build to GitHub Actions.
which makes easier for macOS users to try latest DeSmuME build.

ci: Add macOS app Build

---

.github/workflows/build_interface.yml

it's highly annoying to get the red X for any push or pull request
because mac os x interface build is broken since december.
fix it by installing glib which meson complains about.

CI: fix mac os interface build, to make everything green again

---

.github/workflows/build_win.yml

When we were fiddling around trying to get the Windows build working in GitHub actions, the "setup-msbuild" action in the build job was set to v1.0.3. This version doesn't support the "msbuild-architecture" variable, which allows for use of the 64-bit build tools.
This PR changes to v1.1 of the action, which fixes the above and also gets rid of this warning in the build job:
Sample run here: https://github.com/SimonAfek/desmume/actions/runs/1916084159

Fix build action warning + use 64-bit build tools

---

desmume/README.INT

I noticed the build instructions for Linux and Mac were not updated when the build system was migrated to Meson. This fixes that.

Update build instructions for the DLL/SO

---

desmume/src/frontend/interface/interface.cpp
desmume/src/frontend/interface/interface.h
desmume/src/lua-engine.cpp

I was going nuts today trying to figure out why writing the same value to a register just paniced the processor.
It seems the Lua interface and in result the interface frontend asume `unsigned long` to be 32bits, which it isn't neccesarily. I updated the types used to be the proper sized integers.

Fix register read/write hooks (potentially) using wrong integers sizes

---

.github/workflows/release_tarball.yml

once a tag has been pushed and "draft new release" using that tag finalized, a source tarball will be automatically uploaded to that release, as can be seen here: https://github.com/rofl0r/desmume-gtk2/releases/tag/v9.99.91

CI: add action to create release tarball

---

desmume/src/slot1.cpp

The only time we need fatDir to be not-empty is when we are using a custom FAT directory (ie. `slot1_R4_path_type/sameAsRom == false`). When we are using the ROM path (`slot1_R4_path_type/sameAsRom == true`), fatDir is not even used, and we should be able to load the FAT image.

Allow scanDir() to operate when fatDir is empty

---

desmume/src/NDSSystem.cpp
desmume/src/utils/decrypt/decrypt.cpp
desmume/src/utils/decrypt/decrypt.h

This avoids some issues when loading homebrew that has CRC16 != 0.

Decide `hasSecureArea` from `DecryptSecureArea()`

---

desmume/src/frontend/posix/cli/main.cpp

The proposed PR applies a minor fix to the Linux CLI frontend to correctly assign the GBA SRAMPath. The issue is detailed in #536 . Briefly, before the GBA SRAMPath would be assigned as `.gba.sav` whenever the GBA ROM Path ended in `.sav`. The new method ensures that if a GBA ROM has path `gamerom.gba` the SRAM path will become `gamerom.sav`. Moreover, the proposed changes also allow for different file extensions of the GBA ROM and/or no file extension at all.

Fixed GBA SRAMPath in posix CLI

---

desmume/src/NDSSystem.cpp

As of a while ago (maybe since the start?), ndstool generates `gameCode = ####` in the ROM header. This is generally a very good sign that the application is homebrew, as commercial games do not use this character in their `gameCode`.

Check `gameCode==####` for homebrew

---

desmume/src/frontend/posix/gtk/main.cpp

The entry index gets converted to a (temporary) string, from which a
pointer to internal data is taken and only consumed outside the loop,
where parent variable no longer exists.

Fix use of internal storage of temporary buffer

---

desmume/src/frontend/posix/shared/ctrlssdl.cpp
desmume/src/frontend/posix/shared/ctrlssdl.h

fixes #563
unlike #566, this also fixes the gtk2 frontend automatically.

posix: properly fix size mismatch of keyboard/joystick_cfg arrays

---

.github/workflows/build.yml

this makes sure the build of cli/gtk2 frontend doesnt break, and also serves as some sort of documentation for the build process on ubuntu.

CI: add build job for linux/GTK2

---

desmume/src/saves.cpp

Keep only maximum of <n> (200 by default) backups when creating backup during state load.
Once maximum files exist overwrite oldest one.
Also added ability to define <n> in desmume.ini under [General] BackupSavesMax=<n>
Based on discussion in https://github.com/TASEmulators/desmume/issues/522

Limit maximum number of backups files for load state backup

---

desmume/src/MMU.cpp

Previously, the overflow case "-MAX/-1" would cause a floating point exception and crash (visible in the [rockwrestler](https://github.com/RockPolish/rockwrestler) DSMATH tests). I special-cased this to handle it correctly. I also added the behavior where the sign extension is inverted on a divide by 0 with a 32 bit result. These are enough to get through and pass all the aforementioned DSMATH tests without crashing.
All the information I used is on GBATEK and I verified the tests pass on hardware.

Fix division edge cases and prevent crash

---

desmume/src/arm_instructions.cpp

warning: use of bitwise '&' with boolean operands [-Wbitwise-instead-of-logical]
Reported by clang 15.

Fix a few compiler warnings

---

desmume/src/Database.cpp

In the `RegionXXXForCode` function, if the value of `code` is 0, then `strchr` will return a pointer to the end of the `regions_index` string and thus the index calculation (`found-regions_index`) will result in returning an out-of-bounds value. This PR adds a check to prevent this behavior. ASan output is below for reference.
```
=================================================================
==5084==ERROR: AddressSanitizer: global-buffer-overflow on address 0x56366011b340 at pc 0x56365ff093bd bp 0x7ffc411d1ff0 sp 0x7ffc411d1fe8
READ of size 8 at 0x56366011b340 thread T0
#0 0x56365ff093bc in Database::RegionXXXForCode(char, bool) /home/hjung/desmume/desmume/src/frontend/posix/../../Database.cpp:377:20
#1 0x56365f7b5e6a in GameInfo::populate() …
```

Fix out-of-bounds index access

---

.github/workflows/build.yml

hopefully will prevent the OOM killer from kicking in.

CI: limit autoconf build to 8 processes

---

.github/workflows/build_win.yml

Fixes this warning about deprecated NodeJS versions in the GitHub-supplied actions `checkout` and `upload-artifact`:
Sample run [here](https://github.com/SimonAfek/desmume/actions/runs/4936859243).

Windows CI: Update deprecated github actions

---

desmume/src/frontend/posix/gtk/main.cpp

The audio volume level would reset to the default 128 whenever a ROM is loaded, audio is disabled and re-enabled, or anything else that would cause a call to `SPU_ChangeSoundCore`.
This PR calls `SPU_SetVolume` instead of `SNDSDLSetAudioVolume` to make the volume change persistent. Additionally the volume slider is now capped at 100 instead of 128. Volume in the config file will also use the cap of 100. A side effect of this is that users who have volume >100 in their config will have oversaturated audio until they lower the volume.
Also, closing the `Set audio volume` window will behave the same as pressing `Cancel` on it. I'm not sure if this is a welcome change, but it makes more sense to me.
I only made the changes to `posix/gtk` as it's the only framework I could easily build and …

Fix audio volume resetting on posix/gtk

---

desmume/src/addons/slot2_hcv1000.cpp
desmume/src/frontend/windows/gbaslot_config.cpp
desmume/src/frontend/windows/gbaslot_config.h
desmume/src/frontend/windows/main.cpp
desmume/src/slot2.h

- Off-by-one in GetWindowText call that was limiting barcode data to 15 characters
- Limit string read from ini to 16 characters
- Add function to the addon to set the barcode data from an std::string to make things cleaner

Slot2: Sega Card Reader fixes

---

desmume/src/frontend/modules/osd/agg/agg2d.inl
desmume/src/frontend/modules/osd/agg/agg_osd.cpp
desmume/src/frontend/modules/osd/agg/agg_osd.h
desmume/src/frontend/modules/osd/agg/aggdraw.cpp
desmume/src/frontend/modules/osd/agg/aggdraw.h
desmume/src/frontend/posix/gtk/config.cpp
desmume/src/frontend/posix/gtk/config_opts.h
desmume/src/frontend/posix/gtk/main.cpp
desmume/src/frontend/posix/gtk/menu.ui
desmume/src/frontend/posix/gtk/meson.build
desmume/src/frontend/posix/meson.build

My previous PR (implement GPU scale factor for GTK) created a problem with OSD: it is drawn without scaling, so when scale factor is > 1, OSD becomes small. I implemented OSD scaling. Scaling most elements like rectangles and ellipses seems trivial, but I could not figure out how to scale raster fonts. So instead I used vector fonts. Most of the code to work with vector fonts was already in AGG OSD files, I only added some missing functions and made using vector fonts optional via flag. By default vector fonts are disabled to keep other frontends working as before. It is frontend's job to provide a font file and set this flag. In GTK frontend I use fontconfig to locate monospace font file in the system. Also for vector fonts I could not figure out how to set background, so I made outlines …

GTK: make OSD scalable

---

desmume/src/libretro-common/file/file_path.c

strdup and realpath are only declared by glibc's headers if _XOPEN_SOURCE >= 500.
(I checked libretro-common upstream, and this doesn't seem to have been fixed there; maybe they're not building with -std=c99 or similar. Previously it would just have produced a warning but an implicit declaration is a hard error with GCC 14.)

libretro-common: fix implicit declarations

---

desmume/src/path.cpp

(Regression from commit 3511e14. Fixes #817.)  
`ReadKey(...)`(old) and `ReadKeyW(...)`(new in 3511e14) behave differently in regards to how they call `GetDefaultPath(...)`.  
In `ReadKey(...)` the first parameter of `GetDefaultPath(...)` is the value that is read by `GetPrivateProfileString(...)`.  
In `ReadKeyW(...)` the first parameter of `GetDefaultPath(...)` is the variable `temppath` (an empty string).  
Fixed by copying the value read by `GetPrivateProfileStringW(...)` into `temppath` before calling `GetDefaultPath(...)`.  
Paths are now working as intended:

Windows Port: Fix empty defaults for path settings

---

desmume/src/frontend/cocoa/userinterface/DisplayWindowController.mm

This pull request fix a bug where the touchscreen coordinates were erroneous when using a mixed retina/non-retina display setup on macOS. I don't know if those defines are still necessary, but I kept them for code consistency.

Cocoa Port: Fix mixed retina/non-retina display touchscreen bug

---

desmume/src/cheatSystem.cpp
desmume/src/cheatSystem.h
desmume/src/frontend/posix/gtk/Makefile.am
desmume/src/frontend/posix/gtk/cheatsGTK.cpp
desmume/src/frontend/posix/gtk/meson.build
desmume/src/frontend/posix/gtk/utilsGTK.cpp
desmume/src/frontend/posix/gtk/utilsGTK.h
desmume/src/frontend/posix/gtk2/Makefile.am
desmume/src/frontend/posix/gtk2/cheatsGTK.cpp
desmume/src/frontend/posix/gtk2/meson.build
desmume/src/frontend/posix/gtk2/utilsGTK.cpp
desmume/src/frontend/posix/gtk2/utilsGTK.h

Summary:
The Linux GTK frontend's cheat menu now reads Action Replay codes from a game's `dct` file and adds them to a seperate section where users can add, remove, toggle, and modify them correctly and conveniently.
A couple changes were also made to the internal cheats' section of the menu to make it harder to misuse:
- The "Offset" field has been changed to an "Address" field, and now expects 7 nibbles of hexadecimal data (fixes #725).
- The value can no longer be outside of its logical range (for example, a 1-byte cheat is capped at 255).
Notes:
Action Replay code entry still leaves something to be desired. The scroll window sometimes doesn't scroll all of the way down and there is no size cut-offs, so long codes can consume far too much space. Coding two new GTK objects to get …

[Linux - GTK3/GTK2] Action Replay code menu (+ other cheat menu improvements)

---

desmume/src/MMU.cpp
desmume/src/frontend/windows/console.cpp
tools/nds_firmware_tool/src/console.cpp

Fix ensata sound register emulation.

---

desmume/src/frontend/posix/gtk/main.cpp
desmume/src/frontend/posix/gtk2/main.cpp
desmume/src/frontend/posix/gtk2/meson.build
desmume/src/frontend/posix/meson.build
desmume/src/frontend/posix/meson_options.txt
desmume/src/frontend/posix/shared/ctrlssdl.cpp

1. Unbind gamepad keys by default. The default bindings may fit one gamepad model but work weirdly with another causing issues like #834
2. Use non-blocking method to obtain gamepad keys/axes during configuration to avoid visible emulator freeze and possible deadlock (see #843)

[Linux/GTK3] Some gamepad input rework

---

desmume/src/OGLRender.cpp

Found with Valgrind while cleaning up the Linux cheat menu code.
The length calculated for `versionSubstring` is the number of bytes in the substring, but that did not account for the null terminator necessary when putting the data in its own string allocation. Thus, the `sscanf` call could read outsize the allocation bound.
The fix is very simple: provide the extra byte necessary to store a null terminator and do so.

fix: null-terminate versionSubstring in OGLGetDriverVersion

---

desmume/src/frontend/interface/interface.cpp
desmume/src/frontend/posix/gtk/main.cpp
desmume/src/frontend/posix/gtk2/main.cpp
desmume/src/frontend/posix/shared/ctrlssdl.cpp
desmume/src/frontend/posix/shared/ctrlssdl.h

Support for reconnecting gamepads and connecting new ones while desmume is already running. For that I added corresponding event processing to ctrlssdl, also modifying how connected joystick info is stored (and fixing joystick uninit in the process: previously open_joysticks array was allocated but never populated, but used in uninit function nevertheless), and how pressed button id is calculated (previously joystick instance id was used but it changes every time gamepad is reconnected, so now joystick index is used instead).
This can be backported to GTK2 but GTK2 is now ahead of my branch after recent commits, so please review this PR as it is for now.

Linux/GTK3: add gamepad hotplug support

---

desmume/src/frontend/posix/gtk/graphics.ui
desmume/src/frontend/posix/gtk/main.cpp
desmume/src/frontend/posix/gtk/menu.ui

Port recent changes to GPU scaling/window sizes from GTK2 to GTK3.

Port 0.5 GPU scaling increments/window sizes to GTK3

---

desmume/src/frontend/posix/shared/egl_3Demu.cpp

To properly use prime render offload eglGetPlatformDisplay must be used instead of eglGetDisplay. It's available in EGL 1.5, so use it if available, fallback to eglGetDisplay if not. Helps #864.

EGL: use eglGetPlatformDisplay if available

---

desmume/src/ROMReader.cpp

MemROMReaderWrite was not working for 1 byte length because it would copy the current mem's byte into the source buffer instead of copying source to mem.

Bugfix: MemROMReaderWrite not working for size=1

---

desmume/src/movie.cpp

This can be easily testing by pressing the lid toggle button, pressing and holding the mic hotkey and pressing the lid toggle button again.
Previously, this would write `MOVIECMD_MIC` as command instead of ORing it together with the `MOVIECMD_LID`, resulting in a desync when playing back the movie as the second lid toggle would be missing.

fix movie command flags not actually being OR'd together

---

desmume/src/frontend/posix/cli/main.cpp
desmume/src/frontend/posix/gtk/main.cpp
desmume/src/frontend/posix/gtk2/main.cpp
desmume/src/frontend/posix/shared/ctrlssdl.cpp
desmume/src/frontend/posix/shared/ctrlssdl.h

For this I had to somewhat rework SDL input handling and add game controller api usage: if joystick is recognized as a game controller by SDL I open it as a game controller, otherwise fallback to generic joystick open. This is required to receive touchpad events. Additionally I have to filter out joystick events if joystick is open as game controller, otherwise there will be double events.
Touchpad finger coords are translated into touchscreen coords thus making touchpad act like touchscreen. This may be what is wanted in #897, but I implemented it only for Linux GTK frontends. Cli frontend must process changes in touchpad_status structure for touchpad translation to work (just like it does for mouse_status structure).
Note that hidraw access permissions are required to use touchpad, i.e. …

Linux/GTK: add support for gamepad touchpad -> touch screen input
